CREATE DATABASE IF NOT EXISTS `ATHENEA`  DEFAULT CHARACTER SET utf8;
USE `ATHENEA`;

 SET @OLD_CHARACTER_SET_CLIENT = @@CHARACTER_SET_CLIENT ;
 SET @OLD_CHARACTER_SET_RESULTS = @@CHARACTER_SET_RESULTS ;
 SET @OLD_COLLATION_CONNECTION = @@COLLATION_CONNECTION ;
 SET NAMES utf8;
 SET @OLD_TIME_ZONE = @@TIME_ZONE;
 SET TIME_ZONE = '+00:00';
 SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
 SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
 SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO';
 SET @OLD_SQL_NOTES = @@SQL_NOTES, SQL_NOTES = 0;


GRANT ALTER, SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX
ON ATHENEA.*
TO athenea@'%'
IDENTIFIED BY 'athenea';

GRANT ALTER, SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX
ON ATHENEA.*
TO athenea@localhost
IDENTIFIED BY 'athenea';

--
-- Table structure for table `USERS`
--

DROP TABLE IF EXISTS `USERS`;
 SET @saved_cs_client = @@character_set_client;
 SET character_set_client = utf8;
CREATE TABLE `USERS` (
  `EMAIL`    VARCHAR(20)  NOT NULL,
  `PASSWORD`     VARCHAR(20) NOT NULL,
  `NAME` VARCHAR(30)  NOT NULL,
  PRIMARY KEY (`EMAIL`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;
 SET character_set_client = @saved_cs_client;

--
-- Dumping data for table `USERS`
--

LOCK TABLES `USERS` WRITE;
ALTER TABLE `USERS`
  DISABLE KEYS;
INSERT INTO `USERS`
VALUES ('unaizuzu@gmail.com', 'toor', 'Unai'), ('ruben.sancor@opendeusto.es', 'lol', 'Ruben'),
  ('g.virum@opendeusto.es', 'toor12', 'Gaizka'), ('aritz.badiola@opendeusto.es', '1234', 'Aritz');
ALTER TABLE `USERS`
ENABLE KEYS;
UNLOCK TABLES;
SET TIME_ZONE = @OLD_TIME_ZONE;

 SET SQL_MODE = @OLD_SQL_MODE ;
 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
 SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
 SET CHARACTER_SET_CLIENT = @OLD_CHARACTER_SET_CLIENT;
 SET CHARACTER_SET_RESULTS = @OLD_CHARACTER_SET_RESULTS;
 SET COLLATION_CONNECTION = @OLD_COLLATION_CONNECTION;
 SET SQL_NOTES = @OLD_SQL_NOTES;


